apiVersion: v1
data:
  AdminPortalURL: aHR0cHM6Ly8yZjQwY2Y2ZDViNGNkNjVjYmQwZWE3YzBiMTEyNGQ1MTFkODBmODk4YTk3NjE1NWY2OGYwMTI5ZDkzYmI5ZmQ3QHJlZGVzLWFkbWluLmFwcHMub2NwLTAxLnRkaWdpdGFsLXZpdm8uY29tLmJy
kind: Secret
metadata:
  creationTimestamp: null
  name: apicast-configuration-url-secret
  namespace: redes-3scale-apicast
type: Opaque
