apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: apicast
  namespace: redes-3scale-apicast-dev
spec:
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - 3scale-api-management
  ingress:
    enabled: true
