{
 "title": "3scale / Apicast Services",
 "tags": [
  "3scale",
  "apicast"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "redes-3scale-amp" },
   { "name": "env", "label": "environment", "query": "production,staging" },
   {
    "name": "service_id",
    "query": "label_values(total_response_time_seconds_bucket{namespace='$namespace', pod=~'apicast-$env.*'}, service_id)"
   },
   {
    "name": "service_name",
    "query": "label_values(total_response_time_seconds_bucket{namespace='$namespace', pod=~'apicast-$env-.*', service_id='$service_id'}, service_system_name)"
   },
   { "name": "percentile", "query": "99, 95, 90, 80, 70, 50" }
  ]
 },
 "panels": [
  { "title": "$service_id - $service_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service_id" },
  {
   "title": "Upstream HTTP status codes (per second rate)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(upstream_status{namespace='$namespace', pod=~'apicast-$env.*', service_id='$service_id'}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total request time vs upstream request time (${percentile}th percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(total_response_time_seconds_bucket{namespace='$namespace', pod=~'apicast-$env.*', service_id='$service_id'}[1m])) by (le))",
     "legendFormat": "Total request time"
    },
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(upstream_response_time_seconds_bucket{namespace='$namespace', pod=~'apicast-$env.*', service_id='$service_id'}[1m])) by (le))",
     "legendFormat": "Upstream request time"
    }
   ]
  },
  {
   "title": "Response time heatmap (by time bucket)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(total_response_time_seconds_bucket{namespace='$namespace', pod=~'apicast-$env-.*', service_id='$service_id'}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upstream response time heatmap (by time bucket)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(upstream_response_time_seconds_bucket{namespace='$namespace', pod=~'apicast-$env.*', service_id='$service_id'}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}