apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: staging-movel
  namespace: redes-3scale-apicast
spec:
  adminPortalCredentialsRef:
    name: apicast-configuration-url-secret
  enabledServices:
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '22'
  extendedMetrics: true
  logLevel: info
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  responseCodesIncluded: true
  timezone: America/Sao_Paulo
